"use client";

import { useState } from "react";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  function prepareQuote(event) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const body = `Name: ${data.get('name')}\nPhone: ${data.get('phone')}\nEmail: ${data.get('email')}\nLocation: ${data.get('location')}\nService: ${data.get('service')}\n\n${data.get('message')}`;
    window.location.href = 'mailto:sales@rmoutdoorservices.com?subject=' + encodeURIComponent('Quote request: ' + data.get('service')) + '&body=' + encodeURIComponent(body);
  }
  return (<>

<div className="top"><div className="wrap"><span>Serving Fairbanks & North Pole, Alaska</span><span>24/7 operations during major snow events</span></div></div>
<header className="header"><nav className="wrap nav" aria-label="Main navigation"><a className="brand" href="#home" aria-label="R and M Outdoor Services home"><img src="/logo.png" alt="R & M Outdoor Services LLC logo" width="90" height="75" /><div>R & M<span>OUTDOOR SERVICES</span></div></a><button className="mobile-toggle" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)} aria-controls="navigation">Menu</button><div className={menuOpen ? "links open" : "links"} id="navigation" onClick={() => setMenuOpen(false)}><a href="#services">Services</a><a href="#about">About us</a><a href="#questions">FAQs</a><a href="#contact">Contact</a></div><a className="btn" href="tel:+19074831408">(907) 483-1408</a></nav></header>
<main><section className="hero" id="home"><img src="/plowing.jpeg" alt="R & M’s pickup with a red snowplow on a snowy forest road" fetchPriority="high" /><div className="wrap"><p className="eyebrow">Local people. Alaska-ready equipment.</p><h1>Winter shows up.<br /><em>We clear the way.</em></h1><p className="description">Snow plowing and hard pack removal for Fairbanks and North Pole. Get your driveway back and your day moving.</p><div className="actions"><a className="btn" href="#contact">Request a quote</a><a className="btn outline" href="tel:+19074831408">Call (907) 483-1408</a></div><p className="hero-note">Family & Army Veteran owned · Licensed, bonded & insured</p></div></section>
<div className="trust"><div className="wrap"><span>Built for Interior Alaska</span><span>Snow plowing · Excavation · Grading</span><span>Family & Army Veteran owned</span></div></div>
<section className="section" id="services"><div className="wrap"><div className="intro"><div><p className="eyebrow">Work for every season</p><h2>From deep snow<br />to solid ground.</h2></div><p>One local crew for winter access and the groundwork that comes next.</p></div><div className="cards"><article className="card featured"><div className="number">01 / WINTER</div><h3>Snow plowing</h3><p>Clear snow-covered driveways and tackle stubborn hard pack with a crew that understands Interior Alaska winters.</p><ul><li>Driveway snow clearing</li><li>Hard pack removal</li><li>Major snow event operations</li></ul></article><article className="card"><div className="number">02 / GROUNDWORK</div><h3>Excavation</h3><p>Prepare the ground for your next project, from new foundations to reshaping your property.</p><ul><li>Ground preparation</li><li>Foundation excavation</li><li>Property improvements</li></ul></article><article className="card"><div className="number">03 / FINISHING</div><h3>Grading & gravel</h3><p>Bring uneven surfaces into shape with skid-steer grading and gravel work for driveways and project sites.</p><ul><li>Driveway grading</li><li>Gravel surface leveling</li><li>Site preparation</li></ul></article></div></div></section>
<section className="section operations"><div className="wrap split"><div><p className="eyebrow">Beyond the snowfall</p><h2>The equipment.<br />The people behind it.</h2><p style={{ color: "var(--muted)" }}>From excavation to grading, our work continues long after winter. Bring us your next property project and we’ll talk through the groundwork.</p><a className="btn" href="#contact">Discuss your project</a></div><img className="operations-photo" src="/operations.jpeg" alt="An R & M team member beside an orange Hitachi excavator in a wooded area" loading="lazy" /></div></section><section className="section about" id="about"><div className="wrap split"><img className="about-photo" src="/family.jpeg" alt="The R & M family with their children and a reindeer in a snowy forest" loading="lazy" /><div className="copy"><p className="eyebrow">Your neighbors. Your crew.</p><h2>Local roots.<br />Hands-on service.</h2><p>R & M Outdoor Services is a family and Army Veteran owned business serving Fairbanks and North Pole.</p><p>We bring care, practical experience and the right equipment to every job, whether we’re clearing your driveway or preparing your property for its next chapter.</p><div className="area"><span className="small-label">OUR SERVICE AREA</span><strong>Fairbanks & North Pole</strong><p>Have a property nearby? Call us to discuss your location and project.</p></div></div></div></section>
<section className="section"><div className="wrap"><p className="eyebrow">Let’s get to work</p><h2>A clear path to a cleared property.</h2><div className="process"><div className="step"><span className="small-label">01 / REACH OUT</span><h3>Tell us what you need.</h3><p>Call or email with your location and the snow removal or groundwork you have in mind.</p></div><div className="step"><span className="small-label">02 / MAKE A PLAN</span><h3>Discuss the details.</h3><p>We’ll talk through the property, scope and scheduling so you know what comes next.</p></div><div className="step"><span className="small-label">03 / GET IT DONE</span><h3>Put our crew to work.</h3><p>Once the job is agreed, we bring the equipment and care your property needs.</p></div></div></div></section>
<section className="section about" id="questions"><div className="wrap"><p className="eyebrow">Good to know</p><h2>Before the next snowfall.</h2><div className="faq"><details><summary>Where do you provide service?</summary><p>We serve the Fairbanks and North Pole area. Call (907) 483-1408 to check coverage for your property.</p></details><details><summary>Can you remove hard-packed snow?</summary><p>Yes. Our snow services include plowing and hard pack removal. Tell us about the surface and conditions when you contact us.</p></details><details><summary>Do you operate during major snow events?</summary><p>We have 24/7 operations during major snow events. Contact us to discuss current availability and scheduling.</p></details><details><summary>What do you need for a quote?</summary><p>Your property location, the service you need and a description of the work are a useful starting point. Photos can help us understand the job.</p></details></div></div></section>
<section className="section contact" id="contact"><div className="wrap split"><div><p className="eyebrow">Ready when you need us</p><h2>Let’s clear<br />your to-do list.</h2><p>Tell us about your property and we’ll discuss the next step.</p><a className="contact-link" href="tel:+19074831408">(907) 483-1408</a><a href="mailto:sales@rmoutdoorservices.com">sales@rmoutdoorservices.com</a><div className="hours"><strong>Office hours</strong><br />Monday–Friday, 9am–5pm<br /><br />24/7 operations during major snow events.</div></div><form className="quote" id="quote" onSubmit={prepareQuote}><h3>Request a quote</h3><p>Share a few details to prepare your email to our crew.</p><div className="fields"><div className="field"><label htmlFor="name">Your name</label><input id="name" name="name" required autoComplete="name" /></div><div className="field"><label htmlFor="phone">Phone</label><input id="phone" name="phone" type="tel" autoComplete="tel" /></div><div className="field full"><label htmlFor="email">Email</label><input id="email" name="email" type="email" required autoComplete="email" /></div><div className="field full"><label htmlFor="service">Service</label><select id="service" name="service"><option>Snow plowing & hard pack removal</option><option>Excavation</option><option>Grading & gravel</option></select></div><div className="field full"><label htmlFor="location">Property location</label><input id="location" name="location" required autoComplete="street-address" /></div><div className="field full"><label htmlFor="message">Tell us about the job</label><textarea id="message" name="message" required></textarea></div></div><button className="btn" type="submit">Prepare quote email</button><p className="form-note">Opens your email app. Review and send your request there, or call us directly.</p></form></div></section></main>
<footer className="footer"><div className="wrap"><div><strong>R & M Outdoor Services LLC</strong><br />Fairbanks & North Pole, Alaska</div><span>Family & Army Veteran owned</span><a href="#home">Back to top</a></div></footer>

</>);
}
